"""Imports for Python API.

This file is MACHINE GENERATED! Do not edit.
Generated by: tensorflow/tools/api/generator/create_python_api.py script.
"""
from tensorflow.python import Constant
from tensorflow.python import Identity
from tensorflow.python import Initializer
from tensorflow.python import Ones
from tensorflow.python import Orthogonal
from tensorflow.python import RandomNormal
from tensorflow.python import RandomUniform
from tensorflow.python import TruncatedNormal
from tensorflow.python import VarianceScaling
from tensorflow.python import Zeros
from tensorflow.python.keras._impl.keras.initializers import deserialize
from tensorflow.python.keras._impl.keras.initializers import get
from tensorflow.python.keras._impl.keras.initializers import glorot_normal
from tensorflow.python.keras._impl.keras.initializers import glorot_uniform
from tensorflow.python.keras._impl.keras.initializers import he_normal
from tensorflow.python.keras._impl.keras.initializers import he_uniform
from tensorflow.python.keras._impl.keras.initializers import lecun_normal
from tensorflow.python.keras._impl.keras.initializers import lecun_uniform
from tensorflow.python.keras._impl.keras.initializers import serialize